project:
  type: website

website:
  title: "eRI Compute Cluster Open Forum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cluster.qmd
        text: Cluster
      - href: jobs.qmd
        text: Jobs
      - href: slurm.qmd
        text: Slurm

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

