project:
  type: website

website:
  title: "eRI Open Forum"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Cluster"
        href: cluster.qmd
      - text: "Jobs"
        href: jobs.qmd
      - text: "Slurm"
        href: slurm.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

