project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "eRI Open Forum"
  repo-url: https://github.com/MattBixley/eri-intro
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: overlay
  margin-header: |
    ![](resources/AgResearch.png)
  margin-footer: |
    ![](resources/nesi.png)
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Cluster"
        href: cluster.qmd
      - text: "Jobs"
        href: jobs.qmd
      - text: "Slurm"
        href: slurm.qmd

format:
  html:
#    theme: zephyr
#    theme: sketchy
    theme: morph
    css: styles.css
    toc: true

editor: visual

