project:
  type: website

website:
  title: "eRI Open Forum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cluster.qmd
      - jobs.qmd
      - slurm.qmd

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

