---
title: "Slurm"
---

Some helpful slurm commands to see how your job ran or what is happening on the cluster with more options at the\
[eRI Slurm Reference Guide](https://nznesi.atlassian.net/wiki/spaces/eRI/pages/3010363404/Slurm+Reference+Guide)

#### Slurm

+---------+-----------------------+------------------------------------------------------------------------------+
| Command | Example               | Description                                                                  |
+=========+=======================+==============================================================================+
| sbatch  | `sbatch submit.sl`    | Submits the Slurm script [*submit.sl*](http://submit.sl/ "http://submit.sl") |
+---------+-----------------------+------------------------------------------------------------------------------+
| squeue  | `squeue`              | Displays entire queue.                                                       |
|         |                       |                                                                              |
|         | `squeue --me`         | Displays your queued jobs.                                                   |
|         |                       |                                                                              |
|         | `squeue -p compute`   | Displays queued jobs on the *compute* partition.                             |
+---------+-----------------------+------------------------------------------------------------------------------+
| sacct   | `sacct`               | Displays all the jobs run by you that day.                                   |
|         |                       |                                                                              |
|         | `sacct -S 2024-01-01` | Displays all the jobs run by you since the *1st Jan 2024*                    |
|         |                       |                                                                              |
|         | `sacct -j 123456`     | Displays job *123456*                                                        |
+---------+-----------------------+------------------------------------------------------------------------------+
| scancel | `scancel 123456`      | Cancels job *123456*                                                         |
|         |                       |                                                                              |
|         | `scancel --me`        | Cancels all your jobs.                                                       |
+---------+-----------------------+------------------------------------------------------------------------------+
| sshare  | `sshare -U`           | Shows the Fair Share scores for all projects of which *you* are a member.    |
+---------+-----------------------+------------------------------------------------------------------------------+
| sinfo   | `sinfo`               | Shows the current state of the Slurm partitions.                             |
+---------+-----------------------+------------------------------------------------------------------------------+

#### sbatch

+--------------+----------------------------------------------------+-----------------------------------------------------------+
| Command      | Example                                            | Description                                               |
+==============+====================================================+===========================================================+
| --job-name   | `#SBATCH --job-name=MyJob`                         | The name that will appear when using squeue or sacct      |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --account    | `#SBATCH --account=2024-mjb-sandbox`               | The account that usage will be recorded for.              |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --time       | `#SBATCH --time=DD-HH:MM:SS`                       | Job max walltime\                                         |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --mem        | `#SBATCH --mem=512MB`                              | Memory required per node.                                 |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --partition  | `#SBATCH --partition=compute`                      | Specified job partition                                   |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --output     | `#SBATCH --output=%j_output.out`                   | Standard output file.                                     |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --mail-user  | `#SBATCH --mail-user=matt.bixley@agresearch.co.nz` | Address to send mail notifications.                       |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --mail-type  | `#SBATCH --mail-type=ALL`                          | Will send a mail notification at `BEGIN END FAIL`         |
|              |                                                    |                                                           |
|              | `#SBATCH --mail-type=TIME_LIMIT_80`                | Will send message at *80%* walltime                       |
+--------------+----------------------------------------------------+-----------------------------------------------------------+
| --no-requeue | `#SBATCH --no-requeue`\                            | Will stop job being requeued in the case of node failure. |
+--------------+----------------------------------------------------+-----------------------------------------------------------+

: {tbl-colwidths="\[20,250,450\]"}
